[package]
name = "uoctl"
version = "1.0.0"
edition = "2024"
license = "0BSD"
rust-version = "1.85"  # (keep this in sync with `ci.yaml`)
categories = ["os::linux-apis"]
keywords = ["file", "descriptor", "io", "control"]
repository = "https://github.com/SludgePhD/uoctl"
description = "`ioctl`, uoctl, we all octl. Helpers for binding to `ioctl`-based interfaces."

[dependencies]
libc = "0.2.172"
